//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tortle.PlayerMarker.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModuleSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModuleSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tortle.PlayerMarker.Localization.ModuleSettings", typeof(ModuleSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color of the marker..
        /// </summary>
        internal static string PlayerMarkerColor_Description {
            get {
                return ResourceManager.GetString("PlayerMarkerColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string PlayerMarkerColor_Name {
            get {
                return ResourceManager.GetString("PlayerMarkerColor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PlayerMarkerEnable_Description {
            get {
                return ResourceManager.GetString("PlayerMarkerEnable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string PlayerMarkerEnable_Name {
            get {
                return ResourceManager.GetString("PlayerMarkerEnable_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The displayed marker image..
        /// </summary>
        internal static string PlayerMarkerImage_Description {
            get {
                return ResourceManager.GetString("PlayerMarkerImage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string PlayerMarkerImage_Name {
            get {
                return ResourceManager.GetString("PlayerMarkerImage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transparency of the marker..
        /// </summary>
        internal static string PlayerMarkerOpacity_Description {
            get {
                return ResourceManager.GetString("PlayerMarkerOpacity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string PlayerMarkerOpacity_Name {
            get {
                return ResourceManager.GetString("PlayerMarkerOpacity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of the marker..
        /// </summary>
        internal static string PlayerMarkerSize_Description {
            get {
                return ResourceManager.GetString("PlayerMarkerSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string PlayerMarkerSize_Name {
            get {
                return ResourceManager.GetString("PlayerMarkerSize_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vertical position of the marker..
        /// </summary>
        internal static string PlayerMarkerVerticalOffset_Description {
            get {
                return ResourceManager.GetString("PlayerMarkerVerticalOffset_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Offset.
        /// </summary>
        internal static string PlayerMarkerVerticalOffset_Name {
            get {
                return ResourceManager.GetString("PlayerMarkerVerticalOffset_Name", resourceCulture);
            }
        }
    }
}
